name: recipe_book
description: Recipe book app for creating and sharing recipes

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  ui: 
    path: '../../packages/ui'
  utils:
    path: '../../packages/utils'

  cupertino_icons: ^1.0.2
  
  firebase_core: ^2.11.0
  firebase_auth: ^4.5.0
  cloud_firestore: ^4.6.0
  firebase_storage: ^11.1.2
  cloud_functions: ^4.2.0
  google_sign_in: ^6.1.0
  # firebase_ui_oauth_google: ^1.1.4
  # firebase_ui_auth: ^1.3.0 

  shared_preferences: ^2.0.15
  provider: ^6.0.5
  google_fonts: ^4.0.3
  font_awesome_flutter: ^10.2.1
  go_router: ^6.2.0
  reactive_forms: ^16.1.1
  image_picker: ^0.8.7
  path: ^1.8.0
  skeleton_loader: ^2.0.0+4
  dotted_border: ^2.0.0+3
  google_sign_in_web: ^0.12.0
  url_strategy: ^0.2.0
  smooth_page_indicator: ^1.1.0
  gap: ^3.0.1
  pull_to_refresh: ^2.0.0
  flutter_riverpod: ^2.4.8
  riverpod_annotation: ^2.3.2
  local_auth: ^2.1.7
  dartz: ^0.10.1
  freezed: ^2.4.5

  # firebase_core_desktop: ^1.0.2
  # firebase_auth_desktop: ^1.0.2

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  riverpod_lint: ^2.1.1

# analyzer:
#   enable-experiment:
#     - records
#     - patterns


flutter:

  uses-material-design: true

  assets:
    - assets/tierzero-light.png
    - assets/tierzero-dark.png
    - assets/recipebook-logo.png

  fonts: 
    - family: Lato
      fonts:
        - asset: fonts/Lato/Lato-Black.ttf
        - asset: fonts/Lato/Lato-BlackItalic.ttf
        - asset: fonts/Lato/Lato-Bold.ttf
        - asset: fonts/Lato/Lato-BoldItalic.ttf
        - asset: fonts/Lato/Lato-Italic.ttf
        - asset: fonts/Lato/Lato-Light.ttf
        - asset: fonts/Lato/Lato-LightItalic.ttf
        - asset: fonts/Lato/Lato-Regular.ttf
        - asset: fonts/Lato/Lato-Thin.ttf
        - asset: fonts/Lato/Lato-ThinItalic.ttf
