name: weather_zero
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  ui: 
    path: '../../packages/ui'
  utils:
    path: '../../packages/utils'
  

  cupertino_icons: ^1.0.2
  weather_kit: ^0.2.0
  hooks_riverpod: ^2.4.3
  flutter_riverpod: ^2.4.3
  riverpod_annotation: ^2.2.0
  url_strategy: ^0.2.0
  go_router: ^11.1.4
  flutter_dotenv: ^5.1.0
  dio: ^5.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_generator: ^3.0.0-dev.3
  build_runner: ^2.4.6
  riverpod_lint: ^2.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/.env
