// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        return defaultConfig;
    }
  }

  static const FirebaseOptions defaultConfig = FirebaseOptions(
    apiKey: 'AIzaSyB3nyf6t3bEagfpCWtbQTJq0s6f16BzXpQ',
    appId: '1:520141373589:web:5bfc20eec0b79c0c4b1b9c',
    messagingSenderId: '520141373589',
    projectId: 'niche-48f85',
    storageBucket: 'niche-48f85.appspot.com',
    authDomain: 'niche-48f85.firebaseapp.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3nyf6t3bEagfpCWtbQTJq0s6f16BzXpQ',
    appId: '1:520141373589:web:5bfc20eec0b79c0c4b1b9c',
    messagingSenderId: '520141373589',
    projectId: 'niche-48f85',
    authDomain: 'niche-48f85.firebaseapp.com',
    storageBucket: 'niche-48f85.appspot.com',
    measurementId: 'G-RKH68PX0DS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmOZOkEu7OhULK2Wk5jRBGgnslEtOYwFY',
    appId: '1:520141373589:android:bfdac4560a85dcfb4b1b9c',
    messagingSenderId: '520141373589',
    projectId: 'niche-48f85',
    storageBucket: 'niche-48f85.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpqoHH7RqJm1ty5o9J-niVxc7GuSfeeV8',
    appId: '1:520141373589:ios:b02e9023e80eb6884b1b9c',
    messagingSenderId: '520141373589',
    projectId: 'niche-48f85',
    storageBucket: 'niche-48f85.appspot.com',
    iosClientId:
        '520141373589-c2nbgpm1hj5fa60o40t9l931l594m03f.apps.googleusercontent.com',
    iosBundleId: 'com.example.niche',
  );
}
