// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK5iuTqJQRjaXgndKJJOP57U5swv7YIlM',
    appId: '1:85740521128:web:f5e034fb18ebfdcec1249d',
    messagingSenderId: '85740521128',
    projectId: 'recipebook-2d734',
    // authDomain: 'recipebook-2d734.firebaseapp.com',
    authDomain: 'recipebook.tierzerostudios.com',
    storageBucket: 'recipebook-2d734.appspot.com',
    measurementId: 'G-REEVX0673J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC596TWzR0gbat2YhbWUsKQaxepzfz_HS8',
    appId: '1:85740521128:android:3b8e9f6023aa844bc1249d',
    messagingSenderId: '85740521128',
    authDomain: 'recipebook-2d734.firebaseapp.com',
    projectId: 'recipebook-2d734',
    storageBucket: 'recipebook-2d734.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbSYBcFyLPduRU0DV9_fqZEqJaRMbSjQ8',
    appId: '1:85740521128:ios:e043e09c0471fac1c1249d',
    messagingSenderId: '85740521128',
    projectId: 'recipebook-2d734',
    storageBucket: 'recipebook-2d734.appspot.com',
    androidClientId: '85740521128-of077l6foqstgtjip1i38f5lirk949du.apps.googleusercontent.com',
    iosClientId: '85740521128-b68grts0d0o10e518rcutmtbbo32oj0m.apps.googleusercontent.com',
    iosBundleId: 'com.tierzero.recipeBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbSYBcFyLPduRU0DV9_fqZEqJaRMbSjQ8',
    appId: '1:85740521128:ios:4fbf55461c953544c1249d',
    messagingSenderId: '85740521128',
    projectId: 'recipebook-2d734',
    storageBucket: 'recipebook-2d734.appspot.com',
    androidClientId: '85740521128-of077l6foqstgtjip1i38f5lirk949du.apps.googleusercontent.com',
    iosClientId: '85740521128-esrs3f8tj83rk3gbsvt38qj3f55jceno.apps.googleusercontent.com',
    iosBundleId: 'tierzero.recipe.recipeBook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAK5iuTqJQRjaXgndKJJOP57U5swv7YIlM',
    appId: '1:85740521128:web:12ce76c84b4782adc1249d',
    messagingSenderId: '85740521128',
    projectId: 'recipebook-2d734',
    authDomain: 'recipebook-2d734.firebaseapp.com',
    storageBucket: 'recipebook-2d734.appspot.com',
    measurementId: 'G-CGZKV9FENZ',
  );
}
